INSERT INTO marca (nome) VALUES
('Acura'),
('Alfa Romeo'),
('Aston Martin'),
('Audi'),
('Bentley'),
('BMW'),
('Bugatti'),
('Buick'),
('Cadillac'),
('Chevrolet'),
('Chrysler'),
('Citroen'),
('Dodge'),
('Ferrari'),
('Fiat'),
('Ford'),
('Genesis'),
('GMC'),
('Honda'),
('Hyundai'),
('Infiniti'),
('Jaguar'),
('Jeep'),
('Kia'),
('Koenigsegg'),
('Lamborghini'),
('Land Rover'),
('Lexus'),
('Lincoln'),
('Lotus'),
('Maserati'),
('Mazda'),
('McLaren'),
('Mercedes-Benz'),
('Mini'),
('Mitsubishi'),
('Nissan'),
('Pagani'),
('Porsche'),
('Ram'),
('Rolls-Royce'),
('Subaru'),
('Tesla'),
('Toyota'),
('Volkswagen'),
('Volvo');

INSERT INTO veiculo (veiculo, ano, cor, descricao, vendido, marca_id) VALUES
('Cruze', 2020, 'Azul', 'Descrição do Carro 1', FALSE, 10),
('X6', 2018, 'Preto', 'Descrição do Carro 2', TRUE, 7),
('XC40', 2019, 'Prata', 'Descrição do Carro 3', FALSE, 46);